# Generated by Django 4.1.7 on 2023-11-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LbfApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location_found',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
