# Generated by Django 4.1.7 on 2023-11-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LbfApp', '0003_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('rather_not_say', 'Rather not say')], default='rather_not_say', max_length=100),
        ),
    ]
