# Generated by Django 4.1.7 on 2023-11-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LbfApp', '0004_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('retrieved', 'Retrieved'), ('missing', 'Missing')], default='missing', max_length=100),
        ),
    ]
