# Generated by Django 4.1.7 on 2023-11-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LbfApp', '0008_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='avatar.png', null=True, upload_to='img'),
        ),
    ]
